export const MOCK_PRODUCTS = [
  // PIZZA - 10 items
  {
    id: '1',
    name: 'Margherita',
    description: 'Italian classic with tomato sauce, fior di latte mozzarella, fresh basil leaves, and extra virgin olive oil',
    price: 399,
    image_url: 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=600&q=80',
    category: 'pizza',
    weight: '450 g',
    cooking_time: 15,
    is_popular: true,
    is_available: true,
  },
  {
    id: '2',
    name: 'Pepperoni',
    description: 'Spicy Italian pepperoni, San Marzano tomato sauce, and a generous mozzarella layer - a restaurant classic',
    price: 459,
    image_url: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=600&q=80',
    category: 'pizza',
    weight: '480 g',
    cooking_time: 15,
    is_popular: true,
    is_available: true,
  },
  {
    id: '3',
    name: 'Four Cheese',
    description: 'Mozzarella, gorgonzola, parmesan, and cheddar on a creamy white base without tomato sauce',
    price: 529,
    image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=600&q=80',
    category: 'pizza',
    weight: '460 g',
    cooking_time: 15,
    is_popular: true,
    is_available: true,
  },
  {
    id: '4',
    name: 'Diavola',
    description: 'Spicy Calabrian salami, chili peppers, tomato sauce, mozzarella, and chili flakes for heat lovers',
    price: 479,
    image_url: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?w=600&q=80',
    category: 'pizza',
    weight: '470 g',
    cooking_time: 15,
    is_popular: false,
    is_available: true,
  },
  {
    id: '5',
    name: 'Grilled Chicken',
    description: 'Grilled chicken fillet, bell peppers, mushrooms, tomato sauce, and mozzarella',
    price: 489,
    image_url: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80',
    category: 'pizza',
    weight: '500 g',
    cooking_time: 18,
    is_popular: false,
    is_available: true,
  },
  {
    id: '6',
    name: 'Sicilian',
    description: 'Anchovies, Kalamata olives, capers, tomato sauce, and mozzarella with a coastal Mediterranean flavor',
    price: 509,
    image_url: 'https://images.unsplash.com/photo-1571407970349-bc81e7e96d47?w=600&q=80',
    category: 'pizza',
    weight: '480 g',
    cooking_time: 18,
    is_popular: false,
    is_available: true,
  },
  {
    id: '7',
    name: 'Prosciutto e Funghi',
    description: 'Parma prosciutto, porcini mushrooms, truffle oil, mozzarella, and fresh arugula added after baking',
    price: 569,
    image_url: 'https://images.unsplash.com/photo-1506354666786-959d6d497f1a?w=600&q=80',
    category: 'pizza',
    weight: '490 g',
    cooking_time: 17,
    is_popular: true,
    is_available: true,
  },
  {
    id: '8',
    name: 'Vegetariana',
    description: 'Zucchini, eggplant, artichokes, sun-dried tomatoes, spinach, mozzarella, and tomato sauce',
    price: 449,
    image_url: 'https://images.unsplash.com/photo-1571997478779-2adcbbe9ab2f?w=600&q=80',
    category: 'pizza',
    weight: '470 g',
    cooking_time: 16,
    is_popular: false,
    is_available: true,
  },
  {
    id: '9',
    name: 'Quattro Stagioni',
    description: 'Four sections and four flavors: mushrooms, artichokes, olives, and prosciutto in one pizza',
    price: 549,
    image_url: 'https://images.unsplash.com/photo-1605478371310-a9f1e96b4ff4?w=600&q=80',
    category: 'pizza',
    weight: '510 g',
    cooking_time: 18,
    is_popular: false,
    is_available: true,
  },
  {
    id: '10',
    name: 'Truffle Bianca',
    description: 'White pizza with creamy bechamel, buffalo mozzarella, truffle cream, and parmesan',
    price: 649,
    image_url: 'https://images.unsplash.com/photo-1548369937-47519962c11a?w=600&q=80',
    category: 'pizza',
    weight: '450 g',
    cooking_time: 16,
    is_popular: true,
    is_available: true,
  },
  // PASTA
  {
    id: '11',
    name: 'Carbonara',
    description: 'Spaghetti, egg yolk, guanciale, parmigiano reggiano, and black pepper - no cream, Roman style',
    price: 369,
    image_url: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=600&q=80',
    category: 'pasta',
    weight: '320 g',
    cooking_time: 20,
    is_popular: true,
    is_available: true,
  },
  {
    id: '12',
    name: 'Tagliatelle Bolognese',
    description: 'Fresh tagliatelle with slow-cooked beef ragu, vegetables, red wine, and parmesan',
    price: 389,
    image_url: 'https://images.unsplash.com/photo-1551183053-bf91798d047b?w=600&q=80',
    category: 'pasta',
    weight: '340 g',
    cooking_time: 25,
    is_popular: false,
    is_available: true,
  },
  // STARTERS
  {
    id: '13',
    name: 'Classic Bruschetta',
    description: 'Grilled crispy bread, diced tomatoes, basil, garlic, and olive oil',
    price: 219,
    image_url: 'https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=600&q=80',
    category: 'starters',
    weight: '180 g',
    cooking_time: 8,
    is_popular: false,
    is_available: true,
  },
  {
    id: '14',
    name: 'Chicken Caesar',
    description: 'Chicken fillet, crunchy romaine, parmesan, croutons, and signature Caesar dressing',
    price: 299,
    image_url: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?w=600&q=80',
    category: 'starters',
    weight: '280 g',
    cooking_time: 10,
    is_popular: true,
    is_available: true,
  },
  // DESSERTS
  {
    id: '15',
    name: 'Tiramisu',
    description: 'Classic recipe with mascarpone, espresso, savoiardi biscuits, and cocoa',
    price: 259,
    image_url: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=600&q=80',
    category: 'desserts',
    weight: '180 g',
    cooking_time: 0,
    is_popular: true,
    is_available: true,
  },
  // DRINKS
  {
    id: '16',
    name: 'Homemade Lemonade',
    description: 'Lemon, mint, syrup, and sparkling water for a refreshing Italian-style lemonade',
    price: 149,
    image_url: 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=600&q=80',
    category: 'drinks',
    weight: '400 ml',
    cooking_time: 0,
    is_popular: false,
    is_available: true,
  },
]
